[proforma]
positive = [
    "AA",
    "A[+1]",
    "AA[+1]",
    "A(AAAA)[+1][+1]",
    "UWAKJDNLASNOIJPojkjjdakjn[U:Oxidation]",
    "[+1]-A[+1]-[+1]",
    "AA+AA",
    "EMK[XLMOD:02000#XL1]EVTKSE[XLMOD:02010#XL2]SK[#XL1]PEK[#XL2]AR",
    "SEK[XLMOD:02001#XL1]UENCE//EMEVTK[XLMOD:02001#XL1]SESPEK",
    "EM[Oxidation]EVEES[Phospho]PEK",
    "EM[R: Methionine sulfone]EVEES[O-phospho-L-serine]PEK",
    "EMEVTK[X:DSS#XL1]SESPEK",
    "EM[U:Oxidation]EVEES[U:Phospho]PEK",
    "EM[+15.9949]EVEES[+79.9663]PEK",
    "EM[U:+15.995]EVEES[U:+79.966]PEK",
    "EM[U:+15.995]EVEES[Obs:+79.978]PEK",
    "RTAAX[+367.0537]WT",
    "{Glycan:Hex}EM[Oxidation]EVNES[Phospho]PEK[iTRAQ4plex]",
    "[iTRAQ4plex]-EM[Oxidation]EVNES[Phospho]PEK",
    "[iTRAQ4plex]-EM[Oxidation]EVNES[Phospho]PEK[iTRAQ4plex]-[Methyl]",
    "<[S-carboxamidomethyl-L-cysteine]@C>ATPEILTCNSIGCLK",
    "<[MOD:01090]@C>ATPEILTCNSIGCLK",
    "[Phospho]?EM[Oxidation]EVTSESPEK",
    "[Phospho][Phospho]?[Acetyl]-EM[Oxidation]EVTSESPEK",
    "EM[Oxidation]EVT[#g1]S[#g1]ES[Phospho#g1]PEK",
    "EM[Oxidation]EVT[#g1(0.01)]S[#g1(0.09)]ES[Phospho#g1(0.90)]PEK",
    "[Phospho#s1]?EM[Oxidation]EVT[#s1(0.01)]S[#s1(0.90)]ES[#s1(0.90)]PEK",
    "PROT(EOSFORMS)[+19.0523]ISK",
    "PROT(EOC[Carbamidomethyl]FORMS)[+19.0523]ISK",
    "SEQUEN[Formula:C12H20O2]CE",
    "SEQUEN[Formula:HN-1O2]CE",
    "SEQUEN[Formula:[13C2][12C-2]H2N]CE",
    "SEQUEN[Glycan:HexNAc]CE",
    "EMEVTK[XLMOD:02001#XL1]SESPEK[#XL1]",
    "EMEVTK[XLMOD:02001#XL1]SESPEK",
    "SEK[XLMOD:02001#XL1]UENCE//EMEVTK[XLMOD:02001#XL1]SESPEK",
    "ETFGD[MOD:00093#BRANCH]//R[#BRANCH]ATER",
    "(?DQ)NGTWEM[Oxidation]ESNENFEGYM[Oxidation]K",
    "ELVIS[Phospho|+79.966331]K",
    "ELVIS[Phospho|Obs:+79.978]K",
    "ELV[INFO:xxxxx]IS",
    "ELVIS[Phospho|INFO:newly discovered|INFO:really awesome]K",
    "ELVIS[Phospho|INFO:newly discovered|INFO:Created on 2021-06]K",
    "ELVIS[Phospho|INFO:newly discovered|INFO:Created by software Tool1]K",
    "<13C>ATPEILTVNSIGQLK",
    "EMEVEESPEK/2",
    "EMEVEESPEK+ELVISLIVER",
    "EMEVEESPEK/2+ELVISLIVER/3",
    "A[X:DSS#XL1]//B[#XL1]+C[X:DSS#XL1]//D[#XL1]",
    "<[Carbamidomethyl]@C>ATPEILTCNSIGCLK",
    "<[Oxidation]@C,M>MTPEILTCNSIGCLK",
    "<[TMT6plex]@K,N-term>ATPEILTCNSIGCLK",
    "<[TMT6plex]@K,N-term:A>ATPEILTCNSIGCLK",
    "<[TMT6plex]@K,N-term:A,N-term:B>ATPEILTCNSIGCLK",
    "EM[Oxidation]EVEES[Phospho]PEK",
    "EM[L-methionine sulfoxide]EVEES[O-phospho-L-serine]PEK",
    "EM[R: L-methionine sulfone]EVEES[O-phospho-L-serine]PEK",
    "EMEVTK[X:DSS#XL1]SESPEK",
    "NEEYN[GNO:G59626AS]K",
    "NEEYN[G:G59626AS]K",
    "EM[U:Oxidation]EVEES[U:Phospho]PEK",
    "EM[M:L-methionine sulfoxide]EVEES[M:O-phospho-L-serine]PEK",
    "EM[U:Oxidation]EVEES[M:O-phospho-L-serine]PEK",
    "EM[Oxidation]EVEES[O-phospho-L-serine]PEK",
    "EM[Oxidation]EVE[Cation:Mg[II]]ES[Phospho]PEK",
    "EM[MOD:00719]EVEES[MOD:00046]PEK",
    "EM[UNIMOD:35]EVEES[UNIMOD:56]PEK",
    "EM[RESID:AA0581]EVEES[RESID:AA0037]PEK",
    "EMEVTK[XLMOD:02001#XL1]SESPEK[#XL1]",
    "EMK[XLMOD:02000#XL1]EVTKSE[XLMOD:02010#XL2]SK[#XL1]PEK[#XL2]AR",
    "EMEVTK[XLMOD:02001#XL1]SESPEK",
    "EMEVTK[XLMOD:02001]SESPEK",
    "SEK[XLMOD:02001#XL1]UENCE//EMEVTK[XLMOD:02001#XL1]SESPEK",
    "SEK[XLMOD:02001#XL1]UENCE//EMEVTK[#XL1]SESPEK",
    "EVTSEKC[MOD:00034#XL1]LEMSC[#XL1]EFD",
    "EVTSEKC[L-cystine (cross-link)#XL1]LEMSC[#XL1]EFD",
    "FVNQHLC[MOD:00034#XL1]GSHLVEALYLVC[MOD:00034#XL2]GERGFFYTPK",
    "A//GIVEQC[MOD:00034#XL3]C[#XL1]TSIC[#XL3]SLYQLENYC[#XL2]N",
    "EVTSEKC[XLMOD:02009#XL1]LEMSC[#XL1]EFD",
    "EVTSEKC[X:Disulfide#XL1]LEMSC[#XL1]EFD",
    "EVTSEKC[half cystine]LEMSC[half cystine]EFD",
    "EVTSEKC[MOD:00798]LEMSC[MOD:00798]EFDEVTSEKC[MOD:00798]LEMSC[MOD:00798]EFD",
    "EVTSEKC[UNIMOD:374#XL1]LEMSC[#XL1]EFD",
    "EVTSEKC[Dehydro#XL1]LEMSC[#XL1]EFD",
    "ETFGD[MOD:00093#BRANCH]//R[#BRANCH]ATER",
    "AVTKYTSSK[MOD:00134#BRANCH]//AGKQLEDGRTLSDYNIQKESTLHLVLRLRG-[#BRANCH]",
    "NEEYN[GNO:G59626AS]K",
    "YPVLN[GNO:G62765YT]VTMPN[GNO:G02815KT]NSNGKFDK",
    "EM[+15.9949]EVEES[+79.9663]PEK",
    "EM[+15.995]EVEES[-18.01]PEK",
    "EM[U:+15.9949]EVEES[U:+79.9663]PEK",
    "EM[U:+15.995]EVEES[U:+79.966]PEK",
    "EM[U:+15.995]EVEES[Obs:+79.978]PEK",
    "EM[U:+15.995]EVEES[Obs:+79.978]PEK",
    "RTAAX[+367.0537]WT",
    "SEQUEN[Formula:C12H20O2]CE",
    "SEQUEN[Formula:[13C2]CH6N]CE",
    "SEQUEN[Formula:[13C2][12C-2]H2N]CE",
    "SEQUEN[Glycan:HexNAc1Hex2]CE",
    "[iTRAQ4plex]-EM[Oxidation]EVNES[Phospho]PEK",
    "[iTRAQ4plex]-EM[U:Oxidation]EVNES[Phospho]PEK[iTRAQ4plex]-[Methyl]",
    "{Glycan:Hex}EM[U:Oxidation]EVNES[Phospho]PEK[iTRAQ4plex]",
    "{Glycan:Hex}[iTRAQ4plex]-EM[Oxidation]EVNES[Phospho]PEK[iTRAQ4plex]",
    "{Glycan:Hex}[iTRAQ4plex]-EM[Oxidation]EVNES[Phospho]PEK[iTRAQ4plex]-[Methyl]",
    "{Glycan:Hex}{Glycan:NeuAc}EMEVNESPEK",
    "[Phospho]?EM[Oxidation]EVTSESPEK",
    "[Phospho][Phospho]?[Acetyl]-EM[Oxidation]EVTSESPEK",
    "[Phospho]^2?[Acetyl]-EM[Oxidation]EVTSESPEK",
    "[Phospho]^2?[Acetyl]-EM[Oxidation]EVTSESPEK",
    "EM[Oxidation]EVT[#g1]S[#g1]ES[Phospho#g1]PEK",
    "PRT(ESFRMS)[+19.0523]ISK",
    "PRT(EC[Carbamidomethyl]FRMS)[+19.0523]ISK",
    "EM[Oxidation]EVT[#g1(0.01)]S[#g1(0.09)]ES[Phospho#g1(0.90)]PEK",
    "[Phospho#s1]?EM[Oxidation]EVT[#s1(0.01)]S[#s1(0.09)]ES[#s1(0.90)]PEK",
    "MPGLVDSNPAPPESQEKKPLK(PCCACPETKKARDACIIEKGEEHCGHLIEAHKECMRALGFKI)[Oxidation][Oxidation][half cystine][half cystine]",
    "<13C>ATPEILTVNSIGQLK",
    "<15N>ATPEILTVNSIGQLK",
    "<D>ATPEILTVNSIGQLK",
    "<13C><15N>ATPEILTVNSIGQLK",
    "<[S-carboxamidomethyl-L-cysteine]@C>ATPEILTCNSIGCLK",
    "<[MOD:01090]@C>ATPEILTCNSIGCLK",
    "<[Oxidation]@C,M>MTPEILTCNSIGCLK",
    "<[MOD:01090]@C>[Phospho]?EM[Oxidation]EVTSECSPEK",
    "<[MOD:01090]@C>[Acetyl]-EM[Oxidation]EVTSECSPEK",
    "(?DQ)NGTWEM[Oxidation]ESNENFEGYM[Oxidation]K",
    "(?N)NGTWEM[Oxidation]ESNENFEGYM[Oxidation]K",
    "ELV[INFO:AnyString]IS",
    "ELV[info:AnyString]IS",
    "ELVIS[Phospho|INFO:newly discovered]K",
    "ELVIS[Phospho|INFO:newly discovered|INFO:really awesome]K",
    "ELVIS[Phospho|INFO:newly discovered|INFO:Created on 2021-06]K",
    "ELVIS[Phospho|INFO:newly discovered|INFO:Created by software Tool1]K",
    "ELVIS[U:Phospho|+79.966331]K",
    "ELVIS[U:Phospho|Obs:+79.978]K",
    "ELVIS[Phospho|O-phospho-L-serine]K",
    "ELVIS[UNIMOD:21|MOD:00046]K",
    "ELVIS[UNIMOD:21|Phospho]K",
    "ELVIS[Phospho|O-phospho-L-serine|Obs:+79.966]K",
    "ELVIS[Obs:+79.966|Phospho|Sulfo]K",
    "EMEVEESPEK/2",
    "EM[U:Oxidation]EVEES[U:Phospho]PEK/3",
    "[U:iTRAQ4plex]-EM[U:Oxidation]EVNES[U:Phospho]PEK[U:iTRAQ4plex]-[U:Methyl]/3",
    "EMEVEESPEK/2+ELVISLIVER/3",
    "AA(?AA)",
    "AA(?AA)AA",
    "[dehydro]^3?[gln->pyro-glu]-QSC",
    "[deamidated#1]-FEEAQ[#1]A",
    "[#1]-FEEAQ[deamidated#1]A",
    "AHAM[oxidation#1]TEG-[#1]",
    "AHAM[#1]TEG-[oxidation#1]",
    "SEQUEN[Formula:Zn1:z+2]CE",
    "<[TMT6plex]@K,N-term>ATPEILTCNSIGCLK",
    "<[Oxidation]@W,C-term:G>QATPEILTWCNSIGCLKG",
    "<[Gln->pyro-Glu]@N-term:Q><[Oxidation]@W,C-term:G>QATPEILTWCNSIGCLKG",
    "<[Amidated]@C-term>QATPEILTWCNSIGCLKG",
    "PEPTID-[a-type-ion]",
    "PEPTID[Formula:H-1C-1O-2|Info:d-ion]-[a-type-ion]",
    "PEPTIDE/[Na:z+1]",
    "PEPTIDE/[Na:z+1,H:z+1]",
    "PEPTIDE/[Na:z+1^2]",
    "PEPT[Formula:Zn:z+2]IDE/[Na:z+1^2]",
    "PE[Cation:Al[III]]PTIDE/2",
    "PE[Formula:Al H-3:z+1]PTIDE/1",
    "PE[Formula:Al H-3:z+1]PTIDE/[H:z+1]",
    "[Cation:Al[III]]?PEPTIDE/2",
    "PEPTIDE/[Al H-3:z+1,H:z+1]",
    "PEPTIDEG-[Methyl][Amidated]",
    "[Acetyl][Carbamyl]-QPEPTIDE",
    "[Formula:Zn:z+2|Position:N-term,C-term]^5[Carbamidomethyl|Position:C]^5?MDPETCPCPSGGSCTCADSCKCEGCKCTSCKKSCCSCCPAECEKCAKDCVCKGGEAAEAEAEKCSCCQ",
    "PEPTI(MERMERMERM)[Oxidation|Position:M][Oxidation|Position:M]DE",
    "PEPTI(MERMERMERM)[+32|Position:E]PEPTIDE",
    "PETIEM[Dioxidation#1][Oxidation#2]REM[#1][#2]REM[#2]RM[#1]PEPTIDE",
    "[Oxidation|CoMKP]?PEPT[Phospho]IDE",
    "(>Trypsin)AANSIPYQVSLNS+(>Keratin)AKEQFERQTA",
    "(>P07225 Vitamin K-dependent protein S OS=Homo sapiens OX=9606 GN=PROS1 PE=1 (SV=1) RANGE=12..42)GGK[xlink:dss[138]#XLDSS]IEVQLK//(>P07225 Vitamin K-dependent protein S OS=Homo sapiens OX=9606 GN=PROS1 PE=1 SV=1)KVESELIK[#XLDSS]PINPR/4",
    "(>>>Trastuzumab Fab and coeluting Fc)(>>Fab)(>Heavy chain)EVQLVESGGGLVQPGGSLRLSC[M:l-cystine (cross-link)#XL1]AASGFNIKDTYIHWVRQAPGKGLEWVARIYPTNGYTRYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYC[#XL1]SRWGGDGFYAMDYWGQGTLVTVSSASTKGPSVFPLAPSSKSTSGGTAALGC[M:l-cystine (cross-link)#XL2]LVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYIC[#XL2]NVNHKPSNTKVDKKVEPKSC[M:l-cystine (cross-link)#XL3]DKT//(>Light chain)DIQMTQSPSSLSASVGDRVTITC[M:l-cystine (cross-link)#XL4]RASQDVNTAVAWYQQKPGKAPKLLIYSASFLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYC[#XL4]QQHYTTPPTFGQGTKVEIKRTVAAPSVFIFPPSDEQLKSGTASVVC[M:l-cystine (cross-link)#XL5]LLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYAC[#XL5]EVTHQGLSSPVTKSFNRGEC[#XL3]+(>Fc)HTCPPCPAPELLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGVEVHNAKTKPREEQYNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKALPAPIEKTISKAKGQPREPQVYTLPPSREEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSKLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLSPGK",
]
negative = [
    "<D>A[UNIMODIFY:+2]+<D>A",
    "A[+1]-",
    "[Acetyl]-[Phospho]^2?EM[Oxidation]EVTSESPEK",
    "PRT(EC[Carbamidomethyl]FRMS)[+19.0523]^2ISK",
    "P(RT(ESFRMS)[+19.0523]IS)[+19.0523]K",
    "MPGLVDSNPAPPESQEKKPLK(PCCACPETKKARDACIIEKGEEHCGHLIEAHKECMRALGFKI)[Oxidation]^2[half cystine][half cystine]",
    "ELVIS[Phospho|INFO:newly]discovered]K",
    "<[TMT6plex]>AA",
    "<[TMT6plex#g1]@A>AA",
    "<[TMT6plex#XL1]@A>AA",
    "<[TMT6plex#BRANCH]@A>AA",
    "{TMT6plex#g1}AA",
    "{TMT6plex#XL1}AA",
    "{TMT6plex#BRANCH}AA",
    "AA(?A(A)[+1])AA",
    "AA(A(?A))[+1]AA",
    "()[Dehydro]S",
    "S()[Dehydro]",
    "AA[+1#xl1]/2//AA[#XL1]",
    "(>Tryps)in)AANSIPYQVSLNS+(>Keratin)AKEQFERQTA",
    "(>Tryps(in)AANSIPYQVSLNS+(>Keratin)AKEQFERQTA",
    "(>Trin)AANSIP[+1#XL1]YQVSLNS//(>>Keratin)AKEQ[#XL1]FERQTA",
]
# generate = 10

[modGlobal]
positive = [
    "<[TMT6plex]@K,N-term>",
    "<[TMT6plex]@K,N-terM>",
    "<[TMT6plex]@K,n-terM>",
    "<[TMT6plex]@K,n-tErM>",
    "<[TMT6plex]@K,N-term:A>",
    "<[TMT6plex]@K,N-term:A,N-term:B>",
]

[INT]
positive = ["0", "1", "12347163101713764196123", "00000000000"]
negative = ["", "i", "+1", "000o00"]

[sequenceElement]
positive = ["A", "U", "X", "a", "A[#g1]"]
negative = ["aa", "Asn", "A[#g1", "A(A)"]

[mod]
positive = [
    "[+1]",
    "[U:+1]",
    "[+23.092]",
    "[-23.092]",
    "[14|Obs:+14|UNIMOD:0034|U:methyl]",
    "[Formula:C-1O-1]",
    "[Glycan:Hex1HexNAc2]",
    "[Formula:AlH-3:z1]",
    "[Formula:AlH-3:z+1]",
    "[Formula:H-1:z-1]",
]

[modMass]
positive = ["+23", "-23.0", "+23.0", "U:+23", "Obs:+23"]
negative = ["23", "U:23"]

[modFormula]
positive = ["Formula:Zn:z+2", "Formula:Zn1:z2", "Formula:Na:Z+1"]

[formula]
positive = [
    "N1H3",
    "NH3",
    "C-1O-1",
    "H1H1H1N1",
    "[15N]H3",
    "[15N1]H3",
    "UTeHe",
    "[ 15 N     1 ] H 1",
    "C12H20O2",
    "C12 H20 O2",
    "HN-1O2",
    "[13C2][12C-2]H2N",
    "[13C2]C-2H2N",
    "Zn1",
]
negative = ["Ht1", "15N1", "15 N 1 H 1", "[15NH3", "Z:+1", "Nz:Z--z"]

[adductIon]
positive = ["Na:z+1", "Na:z+1^2"]
negative = ["Na:z--1", "Na", "Naz+1", "Na^1"]

[peptidoformCharge]
positive = [
    "/1",
    "/+1",
    "/-1",
    "/2",
    "/+2",
    "/-10101",
    "/[Na:z+1]",
    "/[Na:z+1^2]",
    "/[Na:z+1,Zn:z+2,H:z+1]",
]
negative = ["/1/1", "/1[Na]"]

[modGlycan]
positive = [
    "Glycan:Hex2HexNAc",
    "Glycan:{C8H14N1O5:z+1}1Hex2",
    "Glycan:{C8H13[15N1]O5}1Hex2",
]

[NAMETEXT]
positive = ["I>>I", "I(III)"]
negative = [">II", ">>>", "(KKK", "LLK()UU)"]
